In [1]:
import numpy as np

In [2]:
# numpy 
# 공학, 수학 대수학을처리하는 용도로 사용..
# 수치계산..
# scalar, vector, matrix, tensor ...
#      배열(1차원) 2차원  3차원

## array

In [6]:
# list: [1,2,3,'a', 'b']
# string : "hello python"

L = [1,4,5,7]

test_arr = np.array(L) # 리스트와 유사 but 차이는 있음
test_arr

array([1, 4, 5, 7])

In [7]:
test_arr[1] # indexing

4

In [9]:
test_arr[1:3] # slicing

array([4, 5])

In [11]:
type(test_arr)

numpy.ndarray

In [12]:
test_arr.shape # 원소가 4개인 1차원 array => vector

(4,)

In [15]:
L = [1,2,3,'python'] # 리스트는 다양한 타입의 값을 같이 사용가능

In [17]:
np.array(L) # np.array는 모든 원소가 동일한 데이터 타입으로 구성된다 => 연산속도가 높다

array(['1', '2', '3', 'python'], dtype='<U11')

In [19]:
L = [1,2,4,3.14]
np.array(L)

array([1.  , 2.  , 4.  , 3.14])

In [21]:
L = [[1,2,4,5], [4,5,6,4], [8,6,4,3]]
L

[[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]]

In [22]:
np.array(L)

array([[1, 2, 4, 5],
       [4, 5, 6, 4],
       [8, 6, 4, 3]])

In [24]:
np.array(L).shape # 2차원 metrix

(3, 4)

In [26]:
np.array(L).ndim

2

In [27]:
t= [[[1,2,4,5], [4,5,6,4], [8,6,4,3]], [[1,2,4,5], [4,5,6,4], [8,6,4,3]]]
t

[[[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]],
 [[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]]]

In [29]:
np.array(t)

array([[[1, 2, 4, 5],
        [4, 5, 6, 4],
        [8, 6, 4, 3]],

       [[1, 2, 4, 5],
        [4, 5, 6, 4],
        [8, 6, 4, 3]]])

In [32]:
np.array(t).shape # 3차원 tensor

(2, 3, 4)

## reshape

In [38]:
L = [[1,2,4,5], [4,5,6,4]]
L

[[1, 2, 4, 5], [4, 5, 6, 4]]

In [39]:
test_mat = np.array(L)
test_mat

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [40]:
test_mat.shape

(2, 4)

In [48]:
test_mat.reshape(4, 2) # matrix

array([[1, 2],
       [4, 5],
       [4, 5],
       [6, 4]])

In [49]:
test_mat.reshape(8) # vector

array([1, 2, 4, 5, 4, 5, 6, 4])

In [50]:
test_mat.reshape(2,2,2) # tensor

array([[[1, 2],
        [4, 5]],

       [[4, 5],
        [6, 4]]])

In [51]:
text_mat.reshape(4,3) # 원소 갯수가 다른 shape으로 reshape되지 않는다..

NameError: name 'text_mat' is not defined

In [52]:
# np.array() array로 형변환, datatype을 지정할 수 있다..

In [55]:
L = [[1,2,4,5], [4,5,6,4]]
np.array(L, str) # np.array(list, type)

array([['1', '2', '4', '5'],
       ['4', '5', '6', '4']], dtype='<U1')

## indexing

In [58]:
tm = np.array(L)
tm

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [60]:
# arr[row_index, col_index]

In [61]:
tm[1, 1]

5

In [62]:
tm[1][1]

5

In [63]:
tm

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [67]:
tm[0, 2] = 10
tm

array([[ 1,  2, 10,  5],
       [ 4,  5,  6,  4]])

In [70]:
tm = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
tm[1, 2]

8

In [72]:
tm[0, 1:3]

array([2, 3])

In [73]:
tm[:, 3]

array([4, 9])

In [74]:
tm[:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [79]:
tm[:, 1:4:2]

array([[2, 4],
       [7, 9]])

## arange

In [82]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [84]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [86]:
list(range(1, 11, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [88]:
list(np.arange(1, 11, 0.5))

[1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5,
 10.0,
 10.5]

In [89]:
list(np.arange(1, 11, 0.1))

[1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000004,
 1.5000000000000004,
 1.6000000000000005,
 1.7000000000000006,
 1.8000000000000007,
 1.9000000000000008,
 2.000000000000001,
 2.100000000000001,
 2.200000000000001,
 2.300000000000001,
 2.4000000000000012,
 2.5000000000000013,
 2.6000000000000014,
 2.7000000000000015,
 2.8000000000000016,
 2.9000000000000017,
 3.0000000000000018,
 3.100000000000002,
 3.200000000000002,
 3.300000000000002,
 3.400000000000002,
 3.500000000000002,
 3.6000000000000023,
 3.7000000000000024,
 3.8000000000000025,
 3.9000000000000026,
 4.000000000000003,
 4.100000000000003,
 4.200000000000003,
 4.3000000000000025,
 4.400000000000003,
 4.5000000000000036,
 4.600000000000003,
 4.700000000000003,
 4.800000000000003,
 4.900000000000004,
 5.0000000000000036,
 5.100000000000003,
 5.200000000000004,
 5.300000000000004,
 5.400000000000004,
 5.5000000000000036,
 5.600000000000004,
 5.700000000000005,
 5.800000000000004,
 5.900000000000004,
 6.00

In [90]:
list(np.arange(1, 11, 0.01))

[1.0,
 1.01,
 1.02,
 1.03,
 1.04,
 1.05,
 1.06,
 1.07,
 1.08,
 1.09,
 1.1,
 1.11,
 1.12,
 1.1300000000000001,
 1.1400000000000001,
 1.1500000000000001,
 1.1600000000000001,
 1.1700000000000002,
 1.1800000000000002,
 1.1900000000000002,
 1.2000000000000002,
 1.2100000000000002,
 1.2200000000000002,
 1.2300000000000002,
 1.2400000000000002,
 1.2500000000000002,
 1.2600000000000002,
 1.2700000000000002,
 1.2800000000000002,
 1.2900000000000003,
 1.3000000000000003,
 1.3100000000000003,
 1.3200000000000003,
 1.3300000000000003,
 1.3400000000000003,
 1.3500000000000003,
 1.3600000000000003,
 1.3700000000000003,
 1.3800000000000003,
 1.3900000000000003,
 1.4000000000000004,
 1.4100000000000004,
 1.4200000000000004,
 1.4300000000000004,
 1.4400000000000004,
 1.4500000000000004,
 1.4600000000000004,
 1.4700000000000004,
 1.4800000000000004,
 1.4900000000000004,
 1.5000000000000004,
 1.5100000000000005,
 1.5200000000000005,
 1.5300000000000005,
 1.5400000000000005,
 1.5500000000000005,
 1.56000

In [92]:
np.arange(1, 21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## operation

In [97]:
tm = np.arange(30).reshape(5,6)
tm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [98]:
tm.sum()

435

In [100]:
tm.mean()

14.5

In [ ]:
# (5,6)

In [101]:
tm.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [102]:
tm.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [104]:
tm.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [105]:
tm.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [106]:
tm.min(axis=1)

array([ 0,  6, 12, 18, 24])

In [107]:
tm.std(axis=0) # 표준 편차 함수

array([8.48528137, 8.48528137, 8.48528137, 8.48528137, 8.48528137,
       8.48528137])

## element wise peration : 원소간 연산

In [109]:
arr_a = np.arange(6).reshape(2,3)

In [110]:
arr_b = np.arange(6).reshape(2,3)

In [114]:
arr_b

array([[0, 1, 2],
       [3, 4, 5]])

In [112]:
arr_a + arr_b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [113]:
arr_a - arr_b

array([[0, 0, 0],
       [0, 0, 0]])

In [115]:
arr_a * arr_b

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [116]:
arr_a == arr_b

array([[ True,  True,  True],
       [ True,  True,  True]])

## Braodcasting
- shape이 서로 다른 array 간에 연산을 하는 경우, shape이 작은 array의 shape이 확장이 되어서
- element간에 연사을 하게 된다..

In [118]:
arr_a + 10 # scalar가 2by3 matrix 로 확장되어서 element wise 연산을 한다..

array([[10, 11, 12],
       [13, 14, 15]])

In [122]:
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
arr_v = np.array([1, 2, 4])
arr_v

array([1, 2, 4])

In [124]:
arr_a + arr_v # arr_v가 확장이 되어 element 끼리 더해짐 [1,2,4] => [[1,2,4],[1,2,4]]

array([[1, 3, 6],
       [4, 6, 9]])

## Boolean indexing
- boolean array를 index로 하여 True에 해당하는 값만을 추출..
- array의 길이와 boolean array의 길이가 같아야 한다..

In [125]:
ta = np.array([1,4,5,6,3,5,6])

In [130]:
# ta에서 5 이상인 값만 출력하시오...

In [131]:
for i in ta:
    if i >= 5:
        print(i)

5
6
5
6


In [132]:
ta >= 5  

array([False, False,  True,  True, False,  True,  True])

In [133]:
ta[ta >= 5] # 데이터 분석시 속도가느려 for문을 잘 사용하지않

array([5, 6, 5, 6])

In [134]:
# ta에서 짝수만 출력하시오..

In [135]:
ta[ta % 2 == 0]

array([4, 6, 6])

In [ ]:
# 1 ~ 100 사이의 정수에서 20 보다 크고 30 보다 작은 3의 배수를 출력하시오.. 
# => boolean indexing을 사용..

In [153]:
tv = np.arange(1, 101)
tv = tv[30 > tv]
tv = tv[tv > 20]
tv = tv[tv%3 == 0]
tv[(30>tv) & (tv>20) & (tv%3 == 0)]

array([21, 24, 27])

In [180]:
tm = np.array([[1,2,3,4], [5,6,8,2]])
tm2 = np.array([[1],[8]])
tm2

array([[1],
       [8]])

In [181]:
tm + tm2

array([[ 2,  3,  4,  5],
       [13, 14, 16, 10]])